app = "personal-finance-tracker-omar"
primary_region = "fra"

[build]

[env]
  DJANGO_SETTINGS_MODULE = "backend.settings"
  PORT = "8000"
  WEB_CONCURRENCY = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "sh -lc 'python manage.py migrate --noinput && if [ -n \"$GOOGLE_CLIENT_ID\" ] && [ -n \"$GOOGLE_CLIENT_SECRET\" ]; then python manage.py setup_google_oauth --domain ${FLY_APP_NAME}.fly.dev --name Production; else echo Skipping Google OAuth setup; fi'"
