app = "personal-finance-tracker-omar"
primary_region = "fra"

[build]

[env]
  DJANGO_SETTINGS_MODULE = "backend.settings"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]