name: Deploy to Fly.io

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # If your secrets live under a GitHub Environment, set its name here
    # and ensure FLY_API_TOKEN, FLY_APP_NAME, DJANGO_SECRET_KEY, DATABASE_URL
    # are defined in that environment. Otherwise, remove this line.
    environment: production
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy to Fly
        env:
          FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # Set secrets on Fly app
          flyctl secrets set \
            DJANGO_SECRET_KEY="$DJANGO_SECRET_KEY" \
            DJANGO_DEBUG=false \
            DJANGO_ALLOWED_HOSTS="${FLY_APP_NAME}.fly.dev" \
            DATABASE_URL="$DATABASE_URL" \
            --app "$FLY_APP_NAME" --detach \
            --access-token "$FLY_API_TOKEN"

          # Deploy app using Dockerfile + fly.toml
          flyctl deploy --remote-only --app "$FLY_APP_NAME" --access-token "$FLY_API_TOKEN"
